# Generated by Django 5.1.15 on 2026-09-15 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.CharField(help_text='Station ID e.g. maitri or bharati', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(default='East Antarctica', max_length=100)),
                ('coordinates', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Maintenance', 'Maintenance')], default='Online', max_length=20)),
                ('last_ping', models.CharField(default='Just now (Telemetry synced)', max_length=100)),
                ('image', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('commissioned_year', models.IntegerField()),
                ('elevation', models.CharField(max_length=100)),
                ('crew_count', models.IntegerField(default=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogisticsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='e.g. Fuel, Food, Water, Medical supplies, Spare parts', max_length=100)),
                ('quantity', models.FloatField(default=100.0)),
                ('unit', models.CharField(default='units', max_length=50)),
                ('reserve_days', models.IntegerField(default=180)),
                ('status', models.CharField(choices=[('NORMAL', 'NORMAL'), ('WARNING', 'WARNING'), ('CRITICAL', 'CRITICAL')], default='NORMAL', max_length=20)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_items', to='stations.station')),
            ],
        ),
        migrations.CreateModel(
            name='LogisticsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_reserve_days', models.IntegerField(default=240)),
                ('fuel_level_liters', models.IntegerField(default=185000)),
                ('food_ration_days', models.IntegerField(default=310)),
                ('water_storage_liters', models.IntegerField(default=48000)),
                ('medical_supply_status', models.CharField(choices=[('Full', 'Full'), ('Good', 'Good'), ('Restock Needed', 'Restock Needed')], default='Full', max_length=30)),
                ('next_resupply_date', models.CharField(default='November 2026', max_length=100)),
                ('expedition_team', models.CharField(default='45th Indian Scientific Expedition to Antarctica (ISEA)', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logistics', to='stations.station')),
            ],
        ),
        migrations.CreateModel(
            name='InfrastructureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Buildings', 'Buildings'), ('Generator', 'Generator'), ('Solar Panels', 'Solar Panels'), ('Water System', 'Water System'), ('Communication System', 'Communication System')], max_length=50)),
                ('status', models.CharField(default='Operational', max_length=50)),
                ('health_percent', models.IntegerField(default=98)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructure_items', to='stations.station')),
            ],
        ),
        migrations.CreateModel(
            name='InfrastructureData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_health_percent', models.IntegerField(default=97)),
                ('life_support_status', models.CharField(choices=[('Nominal', 'Nominal'), ('Warning', 'Warning'), ('Critical', 'Critical')], default='Nominal', max_length=20)),
                ('heating_system_status', models.CharField(choices=[('Nominal', 'Nominal'), ('Warning', 'Warning'), ('Critical', 'Critical')], default='Nominal', max_length=20)),
                ('water_treatment_capacity_lpd', models.IntegerField(default=4200)),
                ('indoor_temp', models.FloatField(default=21.5)),
                ('satellite_uplink_mbps', models.IntegerField(default=50)),
                ('active_sensors', models.IntegerField(default=248)),
                ('total_sensors', models.IntegerField(default=252)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructure', to='stations.station')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('time_label', models.CharField(default='00:00', max_length=50)),
                ('temperature', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('air_pressure_hpa', models.FloatField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environment_history', to='stations.station')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=-28.0)),
                ('wind_speed', models.FloatField(default=42.0)),
                ('wind_direction', models.CharField(default='ESE (115°)', max_length=50)),
                ('wind_chill', models.FloatField(default=-41.0)),
                ('humidity_percent', models.FloatField(default=48.0)),
                ('air_pressure_hpa', models.FloatField(default=986.0)),
                ('uv_index', models.FloatField(default=1.2)),
                ('visibility_km', models.FloatField(default=35.0)),
                ('snow_accumulation_cm', models.FloatField(default=14.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='environment', to='stations.station')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('time_label', models.CharField(default='00:00', max_length=50)),
                ('power_generation_kw', models.FloatField()),
                ('power_consumption_kw', models.FloatField()),
                ('battery_level_percent', models.FloatField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_history', to='stations.station')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_source', models.CharField(default='Polar Diesel & Microgrid', max_length=150)),
                ('power_generation_kw', models.FloatField(default=185.0)),
                ('power_consumption_kw', models.FloatField(default=142.0)),
                ('solar_generation_kw', models.FloatField(default=28.0)),
                ('generator_load_percent', models.FloatField(default=68.0)),
                ('battery_level_percent', models.FloatField(default=94.0)),
                ('daily_usage_kwh', models.FloatField(default=3408.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='energy', to='stations.station')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalTwinModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('living', 'living'), ('energy', 'energy'), ('science', 'science'), ('comms', 'comms'), ('logistics', 'logistics')], max_length=30)),
                ('status', models.CharField(choices=[('Optimal', 'Optimal'), ('Active', 'Active'), ('Warning', 'Warning')], default='Optimal', max_length=30)),
                ('temp', models.CharField(default='+21.0°C', max_length=50)),
                ('power', models.CharField(default='30 kW', max_length=50)),
                ('description', models.TextField()),
                ('x', models.FloatField(default=10.0)),
                ('y', models.FloatField(default=10.0)),
                ('width', models.FloatField(default=30.0)),
                ('height', models.FloatField(default=25.0)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_twin_modules', to='stations.station')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='low', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('timestamp', models.CharField(default='Just now', max_length=100)),
                ('category', models.CharField(default='Operational', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='stations.station')),
            ],
        ),
    ]
